### ISSUE TITLE
Let the package be installed through `CRAN`

### ISSUE THREAD

**Issue by pacmandoh** [teunbrand/ggarrow#7]
Hi, @teunbrand , Thanks for your excellent R pkg ❤️ !
Have you considered publishing ggarrow to CRAN? In China, it is very troublesome to install the R package from github because of the network. I want to use ggarrow as a dependency for my R package. It will be troublesome to install it from github.

**Comment by teunbrand** [comment]
Thanks for the interest!
Alright, here you go; hot off the press: https://cran.r-project.org/package=ggarrow

**Comment by pacmandoh** [comment]
> Thanks for the interest!
> 
> Alright, here you go; hot off the press: https://cran.r-project.org/package=ggarrow

thx! 💗
